// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package evalsrv

import (
	"github.com/dikyayodihamzah/cv-evaluator/pkg/model"
	"github.com/dikyayodihamzah/cv-evaluator/pkg/model/cvweb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvaluationService creates a new instance of MockEvaluationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluationService {
	mock := &MockEvaluationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvaluationService is an autogenerated mock type for the EvaluationService type
type MockEvaluationService struct {
	mock.Mock
}

type MockEvaluationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluationService) EXPECT() *MockEvaluationService_Expecter {
	return &MockEvaluationService_Expecter{mock: &_m.Mock}
}

// GetResult provides a mock function for the type MockEvaluationService
func (_mock *MockEvaluationService) GetResult(jobID string) (*model.BaseResponse, error) {
	ret := _mock.Called(jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetResult")
	}

	var r0 *model.BaseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.BaseResponse, error)); ok {
		return returnFunc(jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.BaseResponse); ok {
		r0 = returnFunc(jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BaseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvaluationService_GetResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResult'
type MockEvaluationService_GetResult_Call struct {
	*mock.Call
}

// GetResult is a helper method to define mock.On call
//   - jobID string
func (_e *MockEvaluationService_Expecter) GetResult(jobID interface{}) *MockEvaluationService_GetResult_Call {
	return &MockEvaluationService_GetResult_Call{Call: _e.mock.On("GetResult", jobID)}
}

func (_c *MockEvaluationService_GetResult_Call) Run(run func(jobID string)) *MockEvaluationService_GetResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEvaluationService_GetResult_Call) Return(baseResponse *model.BaseResponse, err error) *MockEvaluationService_GetResult_Call {
	_c.Call.Return(baseResponse, err)
	return _c
}

func (_c *MockEvaluationService_GetResult_Call) RunAndReturn(run func(jobID string) (*model.BaseResponse, error)) *MockEvaluationService_GetResult_Call {
	_c.Call.Return(run)
	return _c
}

// StartEvaluation provides a mock function for the type MockEvaluationService
func (_mock *MockEvaluationService) StartEvaluation(req cvweb.EvaluationRequest) (string, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for StartEvaluation")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cvweb.EvaluationRequest) (string, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(cvweb.EvaluationRequest) string); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(cvweb.EvaluationRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvaluationService_StartEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEvaluation'
type MockEvaluationService_StartEvaluation_Call struct {
	*mock.Call
}

// StartEvaluation is a helper method to define mock.On call
//   - req cvweb.EvaluationRequest
func (_e *MockEvaluationService_Expecter) StartEvaluation(req interface{}) *MockEvaluationService_StartEvaluation_Call {
	return &MockEvaluationService_StartEvaluation_Call{Call: _e.mock.On("StartEvaluation", req)}
}

func (_c *MockEvaluationService_StartEvaluation_Call) Run(run func(req cvweb.EvaluationRequest)) *MockEvaluationService_StartEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cvweb.EvaluationRequest
		if args[0] != nil {
			arg0 = args[0].(cvweb.EvaluationRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEvaluationService_StartEvaluation_Call) Return(s string, err error) *MockEvaluationService_StartEvaluation_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEvaluationService_StartEvaluation_Call) RunAndReturn(run func(req cvweb.EvaluationRequest) (string, error)) *MockEvaluationService_StartEvaluation_Call {
	_c.Call.Return(run)
	return _c
}
