// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filesrv

import (
	"context"
	"mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// ExtractText provides a mock function for the type MockFileService
func (_mock *MockFileService) ExtractText(filePath string) (string, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ExtractText")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_ExtractText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractText'
type MockFileService_ExtractText_Call struct {
	*mock.Call
}

// ExtractText is a helper method to define mock.On call
//   - filePath string
func (_e *MockFileService_Expecter) ExtractText(filePath interface{}) *MockFileService_ExtractText_Call {
	return &MockFileService_ExtractText_Call{Call: _e.mock.On("ExtractText", filePath)}
}

func (_c *MockFileService_ExtractText_Call) Run(run func(filePath string)) *MockFileService_ExtractText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileService_ExtractText_Call) Return(s string, err error) *MockFileService_ExtractText_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileService_ExtractText_Call) RunAndReturn(run func(filePath string) (string, error)) *MockFileService_ExtractText_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockFileService
func (_mock *MockFileService) Upload(ctx context.Context, path string, files []*multipart.FileHeader) ([]string, error) {
	ret := _mock.Called(ctx, path, files)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*multipart.FileHeader) ([]string, error)); ok {
		return returnFunc(ctx, path, files)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*multipart.FileHeader) []string); ok {
		r0 = returnFunc(ctx, path, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, path, files)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockFileService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - files []*multipart.FileHeader
func (_e *MockFileService_Expecter) Upload(ctx interface{}, path interface{}, files interface{}) *MockFileService_Upload_Call {
	return &MockFileService_Upload_Call{Call: _e.mock.On("Upload", ctx, path, files)}
}

func (_c *MockFileService_Upload_Call) Run(run func(ctx context.Context, path string, files []*multipart.FileHeader)) *MockFileService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*multipart.FileHeader
		if args[2] != nil {
			arg2 = args[2].([]*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_Upload_Call) Return(strings []string, err error) *MockFileService_Upload_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileService_Upload_Call) RunAndReturn(run func(ctx context.Context, path string, files []*multipart.FileHeader) ([]string, error)) *MockFileService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
