// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llmsrv

import (
	"github.com/dikyayodihamzah/cv-evaluator/pkg/model/cvweb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLLMService creates a new instance of MockLLMService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMService {
	mock := &MockLLMService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLMService is an autogenerated mock type for the LLMService type
type MockLLMService struct {
	mock.Mock
}

type MockLLMService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMService) EXPECT() *MockLLMService_Expecter {
	return &MockLLMService_Expecter{mock: &_m.Mock}
}

// EvaluateCVOnly provides a mock function for the type MockLLMService
func (_mock *MockLLMService) EvaluateCVOnly(cvContent string, jobDesc string) (*cvweb.CVResponse, error) {
	ret := _mock.Called(cvContent, jobDesc)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateCVOnly")
	}

	var r0 *cvweb.CVResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*cvweb.CVResponse, error)); ok {
		return returnFunc(cvContent, jobDesc)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *cvweb.CVResponse); ok {
		r0 = returnFunc(cvContent, jobDesc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cvweb.CVResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(cvContent, jobDesc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMService_EvaluateCVOnly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateCVOnly'
type MockLLMService_EvaluateCVOnly_Call struct {
	*mock.Call
}

// EvaluateCVOnly is a helper method to define mock.On call
//   - cvContent string
//   - jobDesc string
func (_e *MockLLMService_Expecter) EvaluateCVOnly(cvContent interface{}, jobDesc interface{}) *MockLLMService_EvaluateCVOnly_Call {
	return &MockLLMService_EvaluateCVOnly_Call{Call: _e.mock.On("EvaluateCVOnly", cvContent, jobDesc)}
}

func (_c *MockLLMService_EvaluateCVOnly_Call) Run(run func(cvContent string, jobDesc string)) *MockLLMService_EvaluateCVOnly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMService_EvaluateCVOnly_Call) Return(cVResponse *cvweb.CVResponse, err error) *MockLLMService_EvaluateCVOnly_Call {
	_c.Call.Return(cVResponse, err)
	return _c
}

func (_c *MockLLMService_EvaluateCVOnly_Call) RunAndReturn(run func(cvContent string, jobDesc string) (*cvweb.CVResponse, error)) *MockLLMService_EvaluateCVOnly_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateCandidate provides a mock function for the type MockLLMService
func (_mock *MockLLMService) EvaluateCandidate(cvContent string, projectContent string, jobDesc string) (*cvweb.CVResponse, error) {
	ret := _mock.Called(cvContent, projectContent, jobDesc)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateCandidate")
	}

	var r0 *cvweb.CVResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*cvweb.CVResponse, error)); ok {
		return returnFunc(cvContent, projectContent, jobDesc)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *cvweb.CVResponse); ok {
		r0 = returnFunc(cvContent, projectContent, jobDesc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cvweb.CVResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(cvContent, projectContent, jobDesc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMService_EvaluateCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateCandidate'
type MockLLMService_EvaluateCandidate_Call struct {
	*mock.Call
}

// EvaluateCandidate is a helper method to define mock.On call
//   - cvContent string
//   - projectContent string
//   - jobDesc string
func (_e *MockLLMService_Expecter) EvaluateCandidate(cvContent interface{}, projectContent interface{}, jobDesc interface{}) *MockLLMService_EvaluateCandidate_Call {
	return &MockLLMService_EvaluateCandidate_Call{Call: _e.mock.On("EvaluateCandidate", cvContent, projectContent, jobDesc)}
}

func (_c *MockLLMService_EvaluateCandidate_Call) Run(run func(cvContent string, projectContent string, jobDesc string)) *MockLLMService_EvaluateCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLLMService_EvaluateCandidate_Call) Return(cVResponse *cvweb.CVResponse, err error) *MockLLMService_EvaluateCandidate_Call {
	_c.Call.Return(cVResponse, err)
	return _c
}

func (_c *MockLLMService_EvaluateCandidate_Call) RunAndReturn(run func(cvContent string, projectContent string, jobDesc string) (*cvweb.CVResponse, error)) *MockLLMService_EvaluateCandidate_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateProject provides a mock function for the type MockLLMService
func (_mock *MockLLMService) EvaluateProject(projectContent string, ragContext string) (*ProjectEvaluation, error) {
	ret := _mock.Called(projectContent, ragContext)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateProject")
	}

	var r0 *ProjectEvaluation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*ProjectEvaluation, error)); ok {
		return returnFunc(projectContent, ragContext)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *ProjectEvaluation); ok {
		r0 = returnFunc(projectContent, ragContext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProjectEvaluation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(projectContent, ragContext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMService_EvaluateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateProject'
type MockLLMService_EvaluateProject_Call struct {
	*mock.Call
}

// EvaluateProject is a helper method to define mock.On call
//   - projectContent string
//   - ragContext string
func (_e *MockLLMService_Expecter) EvaluateProject(projectContent interface{}, ragContext interface{}) *MockLLMService_EvaluateProject_Call {
	return &MockLLMService_EvaluateProject_Call{Call: _e.mock.On("EvaluateProject", projectContent, ragContext)}
}

func (_c *MockLLMService_EvaluateProject_Call) Run(run func(projectContent string, ragContext string)) *MockLLMService_EvaluateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMService_EvaluateProject_Call) Return(projectEvaluation *ProjectEvaluation, err error) *MockLLMService_EvaluateProject_Call {
	_c.Call.Return(projectEvaluation, err)
	return _c
}

func (_c *MockLLMService_EvaluateProject_Call) RunAndReturn(run func(projectContent string, ragContext string) (*ProjectEvaluation, error)) *MockLLMService_EvaluateProject_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractCVInfo provides a mock function for the type MockLLMService
func (_mock *MockLLMService) ExtractCVInfo(cvContent string) (*CVInfo, error) {
	ret := _mock.Called(cvContent)

	if len(ret) == 0 {
		panic("no return value specified for ExtractCVInfo")
	}

	var r0 *CVInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*CVInfo, error)); ok {
		return returnFunc(cvContent)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *CVInfo); ok {
		r0 = returnFunc(cvContent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CVInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cvContent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMService_ExtractCVInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractCVInfo'
type MockLLMService_ExtractCVInfo_Call struct {
	*mock.Call
}

// ExtractCVInfo is a helper method to define mock.On call
//   - cvContent string
func (_e *MockLLMService_Expecter) ExtractCVInfo(cvContent interface{}) *MockLLMService_ExtractCVInfo_Call {
	return &MockLLMService_ExtractCVInfo_Call{Call: _e.mock.On("ExtractCVInfo", cvContent)}
}

func (_c *MockLLMService_ExtractCVInfo_Call) Run(run func(cvContent string)) *MockLLMService_ExtractCVInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLLMService_ExtractCVInfo_Call) Return(cVInfo *CVInfo, err error) *MockLLMService_ExtractCVInfo_Call {
	_c.Call.Return(cVInfo, err)
	return _c
}

func (_c *MockLLMService_ExtractCVInfo_Call) RunAndReturn(run func(cvContent string) (*CVInfo, error)) *MockLLMService_ExtractCVInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ScoreCV provides a mock function for the type MockLLMService
func (_mock *MockLLMService) ScoreCV(cvInfo *CVInfo, jobDesc string, ragContext string) (*CVEvaluation, error) {
	ret := _mock.Called(cvInfo, jobDesc, ragContext)

	if len(ret) == 0 {
		panic("no return value specified for ScoreCV")
	}

	var r0 *CVEvaluation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*CVInfo, string, string) (*CVEvaluation, error)); ok {
		return returnFunc(cvInfo, jobDesc, ragContext)
	}
	if returnFunc, ok := ret.Get(0).(func(*CVInfo, string, string) *CVEvaluation); ok {
		r0 = returnFunc(cvInfo, jobDesc, ragContext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CVEvaluation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*CVInfo, string, string) error); ok {
		r1 = returnFunc(cvInfo, jobDesc, ragContext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMService_ScoreCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScoreCV'
type MockLLMService_ScoreCV_Call struct {
	*mock.Call
}

// ScoreCV is a helper method to define mock.On call
//   - cvInfo *CVInfo
//   - jobDesc string
//   - ragContext string
func (_e *MockLLMService_Expecter) ScoreCV(cvInfo interface{}, jobDesc interface{}, ragContext interface{}) *MockLLMService_ScoreCV_Call {
	return &MockLLMService_ScoreCV_Call{Call: _e.mock.On("ScoreCV", cvInfo, jobDesc, ragContext)}
}

func (_c *MockLLMService_ScoreCV_Call) Run(run func(cvInfo *CVInfo, jobDesc string, ragContext string)) *MockLLMService_ScoreCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *CVInfo
		if args[0] != nil {
			arg0 = args[0].(*CVInfo)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLLMService_ScoreCV_Call) Return(cVEvaluation *CVEvaluation, err error) *MockLLMService_ScoreCV_Call {
	_c.Call.Return(cVEvaluation, err)
	return _c
}

func (_c *MockLLMService_ScoreCV_Call) RunAndReturn(run func(cvInfo *CVInfo, jobDesc string, ragContext string) (*CVEvaluation, error)) *MockLLMService_ScoreCV_Call {
	_c.Call.Return(run)
	return _c
}
