// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ragsrv

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRAGService creates a new instance of MockRAGService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRAGService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRAGService {
	mock := &MockRAGService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRAGService is an autogenerated mock type for the RAGService type
type MockRAGService struct {
	mock.Mock
}

type MockRAGService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRAGService) EXPECT() *MockRAGService_Expecter {
	return &MockRAGService_Expecter{mock: &_m.Mock}
}

// GetRelevantContext provides a mock function for the type MockRAGService
func (_mock *MockRAGService) GetRelevantContext(contextType string, query string) (string, error) {
	ret := _mock.Called(contextType, query)

	if len(ret) == 0 {
		panic("no return value specified for GetRelevantContext")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(contextType, query)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(contextType, query)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(contextType, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRAGService_GetRelevantContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelevantContext'
type MockRAGService_GetRelevantContext_Call struct {
	*mock.Call
}

// GetRelevantContext is a helper method to define mock.On call
//   - contextType string
//   - query string
func (_e *MockRAGService_Expecter) GetRelevantContext(contextType interface{}, query interface{}) *MockRAGService_GetRelevantContext_Call {
	return &MockRAGService_GetRelevantContext_Call{Call: _e.mock.On("GetRelevantContext", contextType, query)}
}

func (_c *MockRAGService_GetRelevantContext_Call) Run(run func(contextType string, query string)) *MockRAGService_GetRelevantContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRAGService_GetRelevantContext_Call) Return(s string, err error) *MockRAGService_GetRelevantContext_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRAGService_GetRelevantContext_Call) RunAndReturn(run func(contextType string, query string) (string, error)) *MockRAGService_GetRelevantContext_Call {
	_c.Call.Return(run)
	return _c
}

// IndexDocument provides a mock function for the type MockRAGService
func (_mock *MockRAGService) IndexDocument(docType string, content string) error {
	ret := _mock.Called(docType, content)

	if len(ret) == 0 {
		panic("no return value specified for IndexDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(docType, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRAGService_IndexDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexDocument'
type MockRAGService_IndexDocument_Call struct {
	*mock.Call
}

// IndexDocument is a helper method to define mock.On call
//   - docType string
//   - content string
func (_e *MockRAGService_Expecter) IndexDocument(docType interface{}, content interface{}) *MockRAGService_IndexDocument_Call {
	return &MockRAGService_IndexDocument_Call{Call: _e.mock.On("IndexDocument", docType, content)}
}

func (_c *MockRAGService_IndexDocument_Call) Run(run func(docType string, content string)) *MockRAGService_IndexDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRAGService_IndexDocument_Call) Return(err error) *MockRAGService_IndexDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRAGService_IndexDocument_Call) RunAndReturn(run func(docType string, content string) error) *MockRAGService_IndexDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function for the type MockRAGService
func (_mock *MockRAGService) Initialize() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRAGService_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockRAGService_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
func (_e *MockRAGService_Expecter) Initialize() *MockRAGService_Initialize_Call {
	return &MockRAGService_Initialize_Call{Call: _e.mock.On("Initialize")}
}

func (_c *MockRAGService_Initialize_Call) Run(run func()) *MockRAGService_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRAGService_Initialize_Call) Return(err error) *MockRAGService_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRAGService_Initialize_Call) RunAndReturn(run func() error) *MockRAGService_Initialize_Call {
	_c.Call.Return(run)
	return _c
}
